### ISSUE TITLE
sending a mail from gmail.cli with attachment in Python2.7 raises UnicodeError when path string is multibyte

### ISSUE THREAD

**Issue by yatt** [paulchakravarti/gmail-sender#8]
Hello

thanks for writing such useful library

I have faced a problem when using this library on 
- Windows10
- Python2.7
- Japanese environment
- sending a mail from gmail.cli
- pass multibyte (cp932) string to parameter `attachment`

reproduction steps below:

In Python2.7
```bat
C:\temp>python -V
Python 2.7.11

C:\temp>c:\Python27\Scripts\virtualenv myenv
New python executable in C:\temp\myenv\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\temp>myenv\Scripts\activate
(myenv) C:\temp>pip install gmail
Collecting gmail
Installing collected packages: gmail
Successfully installed gmail-0.6.2

(myenv) C:\temp>python -m gmail.cli --username %GMAIL_USERNAME% --password %GMAIL_PASSWORD% --to=%GMAIL_USERNAME% --subject サブジェクト --body ボディ --attachment=c:\temp\無題.png
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\temp\myenv\lib\site-packages\gmail\cli.py", line 52, in <module>
    cli()
  File "C:\temp\myenv\lib\site-packages\gmail\cli.py", line 47, in cli
    attachments=results.attachment)
  File "C:\temp\myenv\lib\site-packages\gmail\message.py", line 76, in __init__
    self.root.attach(self._attachment(a))
  File "C:\temp\myenv\lib\site-packages\gmail\message.py", line 114, in _attachment
    attachment.add_header('Content-Disposition','attachment',filename=os.path.basename(a))
  File "c:\python27\Lib\email\message.py", line 411, in add_header
    self._headers.append((_name, SEMISPACE.join(parts)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x96 in position 10: ordinal not in range(128)

(myenv) C:\temp>python -m gmail.cli --username %GMAIL_USERNAME% --password %GMAIL_PASSWORD% --to=%GMAIL_USERNAME% --subject サブジェクト --body ボディ

(myenv) C:\temp>
```

In Python3.6 (It works correctly)
```bat
C:\temp>c:\Python36\python.exe -V
Python 3.6.0

C:\temp>c:\Python36\python.exe -m venv myenv_py3

C:\temp>myenv_py3\Scripts\activate.bat
(myenv_py3) C:\temp>pip install gmail
Collecting gmail
  Using cached gmail-0.6.2.tar.gz
Installing collected packages: gmail
  Running setup.py install for gmail ... done
Successfully installed gmail-0.6.2

(myenv_py3) C:\temp>python -m gmail.cli --username %GMAIL_USERNAME% --password %GMAIL_PASSWORD% --to=%GMAIL_USERNAME% --subject サブジェクト --body ボディ --attachment=c:\temp\無題.png

(myenv_py3) C:\temp>python -m gmail.cli --username %GMAIL_USERNAME% --password %GMAIL_PASSWORD% --to=%GMAIL_USERNAME% --subject サブジェクト --body ボディ

(myenv_py3) C:\temp>
```

**Comment by paulchakravarti** [comment]
Hello,

Thanks for raising this - it's an interesting problem. There are general issues reliably guessing the encoding of filenames. I have put a potential fix in but can't easily reproduce the environment (I don't run Windows or use multibyte encodings). Would you mind trying out the latest version in git (I haven't uploaded to pypi so you will need to grab directly from GitHub).

Thanks, Paul

**Comment by paulc** [comment]
Now in release.
